name: BookManagementApi

on:
  push:
    branches: ['master', 'dev']
    
  pull_request:
    branches: ['master', 'dev']
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Book Management Services
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker-compose.yml'
          services: |
            bookmanagement.db
            bookmanagement.api
          up-flags: '--build -d'
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Start Book Management Services
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker-compose.yml'
          services: |
            bookmanagement.db
            bookmanagement.api
          up-flags: '--build -d'
          
      - name: Test with the dotnet CLI
        run: dotnet test BookManagement.sln
        
