name: BookManagementApi

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker-compose.yml'
          
      - name: Restore NuGet packages
        run: dotnet restore BookManagement.sln
          
      - name: Build
        run: dotnet build BookManagement.sln -c Release --no-restore
